// src/app/layout.tsx
import type { Metadata } from "next";
import "@/styles/globals.css";
import localFont from "next/font/local";
import TopNav from "@/components/TopNav";
import { Analytics } from "@vercel/analytics/react";
import { ReactQueryProvider } from '@/components/providers/ReactQueryProvider';

export const metadata: Metadata = {
  title: "MAD",
  description: "Generated by create next app",
};

const helvetica = localFont({ src: "../../fonts/helvmb__0.ttf" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={helvetica.className}>
      <body>
        <ReactQueryProvider>
          <TopNav />
          {children}
          {process.env.NODE_ENV === 'production' && <Analytics />}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
